### ISSUE TITLE
接收到全局消息me: {{failed MYSQL,Script未知 -1 map[] <nil>} MYSQL,Script未知}

### ISSUE THREAD

**Issue by lscool66** [hw2499/etl-engine#1]
接收到全局消息me: {{failed MYSQL,Script未知 -1 map[] <nil>} MYSQL,Script未知}
![image](https://user-images.githubusercontent.com/16486146/181174094-5c073170-ea39-4324-be8b-ca42413829f6.png)

**Comment by lscool66** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<Graph>
    <Node id="rcp" dbConnection="mysqlout1_rcp" type="DB_INPUT_TABLE" desc="mysqlout1_rcp" fetchSize="1000">
        <Script name="sqlScript">
            <![CDATA[
                            select * from (select * from rcp_sap_tube_state)
 ]]>
        </Script>
    </Node>
    <Node id="rdp" dbConnection="mysqlout1_rdp" type="DB_OUTPUT_TABLE" desc="mysqlout1_rdp" outputFields="tube_id;barcode;state;update_time;update_user_id;approve_user_id;approve_time;approve_state;upload_status;reviewer_lab_id;patient_num;census_address_id;create_time;incept_time;incept_laboratory_id;modify_time;modifier" renameOutputFields="tube_id;barcode;state;update_time;update_user_id;approve_user_id;approve_time;approve_state;upload_status;reviewer_lab_id;patient_num;census_address_id;create_time;incept_time;incept_laboratory_id;modify_time;modifier"></Node>
    <Line id="LINE_01" type="STANDARD" from="rcp" to="rdp" order="0" metadata="rcp_sap_tube_state"></Line>
    <Metadata id="rcp_sap_tube_state">
        <Field name="tube_id" type="string" default="" nullable="false" />
        <Field name="barcode" type="string" default="" nullable="true" />
        <Field name="state" type="string" default="" nullable="true" />
        <Field name="update_time" type="string" default="" nullable="true" />
        <Field name="patient_num" type="string" default="" nullable="false" />
        <Field name="census_address_id" type="string" default="" nullable="false" />
        <Field name="modify_time" type="string" default="" nullable="false" />
    </Metadata>
    <Connection id="mysqlout1_rcp" dbURL="127.0.0.1:3306" database="rcp" username="root" password="66666" type="MYSQL" />
    <Connection id="mysqlout1_rdp" dbURL="127.0.0.1:3306" database="rdp" username="root" password="66666" type="MYSQL" />
</Graph>`

**Comment by hw2499** [comment]
需要在输出节点DB_OUTPUT_TABLE中通过Script标签来写insert语句，以实现写入数据表能力（influxdb不需要用Script标签，mysql,ck都需要通过Script标签），如下：

   <Node id="rdp" type="DB_OUTPUT_TABLE" desc="mysqlout1_rdp" dbConnection="mysqlout1_rdp" outputFields="f1;f2;f3"  renameOutputFields="c1;c2;c3"  batchSize="1000"  >
        <Script name="sqlScript"><![CDATA[
           insert into db1.t1 (c1,c2,c3) values (?,?,?)
    ]]></Script>
    </Node>
更加详细的日志输出，可通过 -logLevel trace 看到

**Comment by hw2499** [comment]
[https://postimg.cc/34xtwD0m](url)

**Comment by hw2499** [comment]
![i1.png](https://i.postimg.cc/2SXFr1rK/i1.png)
