### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by ChunshengLin** [hw2499/etl-engine#2]
no code?

**Comment by hw2499** [comment]
产品定位：目前版本属于免费使用阶段，并采集市场需求，寻找合作组织，后续会跟组织一起包装成商业化商品。

**Comment by lazychanger** [comment]
老板666哇，还能这么玩；选择性开源？

**Comment by hw2499** [comment]
目前在开发OEM内容，随着市场的需求会进行相应的调整，市场决定了方向。

**Comment by jiangshan-baishan** [comment]
不开源就不开源，都能理解，但整个开源仓库，纯纯为了打广告？
