### ISSUE TITLE
支持SQL Server 么

### ISSUE THREAD

**Issue by LZkCrown** [hw2499/etl-engine#4]
有没有计划增加对SQL Server 的支持？

**Comment by hw2499** [comment]
之前没有考虑，因为这边用微软的东西很少，生产环境都是在linux下，有需求可以的

**Comment by hw2499** [comment]
在1.2.6版本中已经适配SQLServer
https://github.com/hw2499/etl-engine/releases/tag/v1.2.6

> 有没有计划增加对SQL Server 的支持？
